setup:
  - name: go # primary language
    commands:
      - "wget https://go.dev/dl/go1.17.6.linux-amd64.tar.gz"
      - "rm -rf /usr/local/go"
      - "tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz" 
  - name: chrome # browsing
    commands:
      - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      - "apt install ./google-chrome-stable_current_amd64.deb"
  - name: ani-cli # for anime ;p
    commands:
      - "wget https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli"
      - "cp ani-cli /usr/local/bin/ani-cli"
      - "chmod +x /usr/local/bin/ani-cli"
  - name: vscode # programming
    commands:
      - "snap install --classic code"
  - name: virtualbox # for virtualization
    commands:
      - "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -"
      - "wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -"
      - "apt-get update"
      - "apt-get install virtualbox"
